// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAtEc5_nKIXBPow4TTO8c5SWu4fc4tAU0',
    appId: '1:384522731108:web:0a5189def1e098727a2971',
    messagingSenderId: '384522731108',
    projectId: 'rskqueue-78608',
    authDomain: 'rskqueue-78608.firebaseapp.com',
    storageBucket: 'rskqueue-78608.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlQv-SqiqzPDneGK_FvWxXDeqohUz13KA',
    appId: '1:384522731108:android:7eed145baa8103187a2971',
    messagingSenderId: '384522731108',
    projectId: 'rskqueue-78608',
    storageBucket: 'rskqueue-78608.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEtumLbzxzZpbtM3lRPGZPkx4Cek26mW8',
    appId: '1:384522731108:ios:7bea9a53fa0367207a2971',
    messagingSenderId: '384522731108',
    projectId: 'rskqueue-78608',
    storageBucket: 'rskqueue-78608.appspot.com',
    androidClientId: '384522731108-1r1t4o5eqenei3s65tngjumjkd0c012n.apps.googleusercontent.com',
    iosClientId: '384522731108-7itmo3bv0ouq9ilu6tnp2852tpr1u438.apps.googleusercontent.com',
    iosBundleId: 'com.example.rskElectronicQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEtumLbzxzZpbtM3lRPGZPkx4Cek26mW8',
    appId: '1:384522731108:ios:4e6b33359207202f7a2971',
    messagingSenderId: '384522731108',
    projectId: 'rskqueue-78608',
    storageBucket: 'rskqueue-78608.appspot.com',
    androidClientId: '384522731108-1r1t4o5eqenei3s65tngjumjkd0c012n.apps.googleusercontent.com',
    iosClientId: '384522731108-ppq7e6va98hse8th8pdg7ap9tel6p6vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.rskElectronicQueue.RunnerTests',
  );
}
